apiVersion: apps/V1
kind: Deployment
metadata:
  name: myappdeployment
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myappcontainer
          image: nginx:1.7.9
          ports:
            - containerPort: 80
