apiVersion: v1
kind: pod
metadata:
  name: redis-pod
spec:
  containers:
    - name: rediscontainer
      image: redis
      volumeMounts:
        - name: vol1
          mountPath: "/etc/vol1"
          readOnly: true
  volumes:
    - name: vol1
      secret:
        secretName: mysecret
