apiVersion: v1
kind: replication controller
metadata: 
  name: myapp-nginx
spec:
  replicas: 3
  selectors:
    app: myapp
  template:
    metadata:
      name: myapp-pod
      label:
        app: myapp
  spec:
    containers:
      - name: myappcontainer
        image: nginx
        ports:
          - containerPort: 80
